spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DragomirAlin/smartfactory-configuration
          clone-on-start: true
          default-label: main

server:
  port: 8888
