spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DragomirAlin/smartfactory-configuration
          clone-on-start: true
          default-label: main

server:
  port: 8888
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.1.32:8761/eureka