spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/Projects/smartfactory/smartfactory-configuration
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.5:8761/eureka