spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Projects/smartfactory/smartfactory-configuration
          clone-on-start: true
          default-label: main

server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.5:8761/eureka